# Site Author
author: 광근 서
title: "개발자 지망생"
subtitle: 어제
avatar: /logo.png
description: "어제의 나보다"
bio: "어제의 나보다 조금 더"
location: "South Korea"
email: gwang92@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: gwang920
  card: summary
logo: logo.png
social:
  name: Gwangguen Seo
  links:
    - https://github.com/gwang920
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
